#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This file is to query and download data from PubMed

@author: Wei Zhao @ Metis, 02/12/2021
"""
#%%
import pandas as pd
from util import *
#%%
def get_first_author(txt):
    
    first = txt[0]['firstname']
    last = txt[0]['lastname']
    if first is None:
        first = "nan"
    if last is None:
        last = 'nan'
    name = [first + ' ' + last]
    return name
#%%
def get_last_author(txt):
    
    first = txt[-1]['firstname']
    last = txt[-1]['lastname']
    if first is None:
        first = "nan"
    if last is None:
        last = 'nan'
    name = [first + ' ' + last]
    return name    
#%%
# def main():
    
fn = '../data/data.pickle'
data = read_from_pickle(fn)

df = pd.DataFrame(data)
# delete article_id, not useful in the analysis
df = df.drop('article_id',axis=1)
df = df.drop('publication_type',axis=1)
idx = df[df['authors'].str.len() == 0].index
df = df.drop(idx, inplace=False)
# df['first_author'] =
    
    # return df
    
# if __name__ == 'main':
    
# df = main()




